export const initialDestinations = [
  {
    id: "dest-goa",
    name: "Goa",
    tagline: "Sun, Sand, Portuguese Heritage & Vibrant Coastal Vibes",
    description: "From the serene golden beaches of South Goa to the buzzing beach shacks and night markets of North Goa, experience rich seafood, water sports, and historic Latin quarters.",
    image_url: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
    tags: ["beach", "food", "nightlife", "water-sports", "relaxation", "heritage"],
    best_season: "Nov - Feb",
    price_band: "mid",
    latitude: 15.2993,
    longitude: 74.1240,
  },
  {
    id: "dest-manali",
    name: "Manali",
    tagline: "Snow-Capped Peaks, High Passes & Himalayan Adventure",
    description: "Nestled in the Beas River valley, Manali is India's prime gateway for trekking, paragliding in Solang, Rohtang snowy excursions, and cozy cedar forests.",
    image_url: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&auto=format&fit=crop&q=80",
    tags: ["hill-station", "adventure", "trekking", "snow", "relaxation", "nature"],
    best_season: "Oct - Jun",
    price_band: "mid",
    latitude: 32.2432,
    longitude: 77.1892,
  },
  {
    id: "dest-jaipur",
    name: "Jaipur",
    tagline: "The Pink City of Maharajas, Palaces & Vibrant Bazaars",
    description: "Marvel at Amber Fort, Hawa Mahal, authentic Rajasthani thalis, artisan block-printing workshops, and astronomical wonders at Jantar Mantar.",
    image_url: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
    tags: ["culture", "heritage", "palaces", "food", "shopping", "photography"],
    best_season: "Oct - Mar",
    price_band: "mid",
    latitude: 26.9124,
    longitude: 75.7873,
  },
  {
    id: "dest-munnar",
    name: "Munnar",
    tagline: "Rolling Emerald Tea Estates, Misty Hills & Wild Elephants",
    description: "Perched in the Western Ghats of Kerala, Munnar offers endless sprawling tea plantations, cool mountain breeze, waterfalls, and spice sanctuary treks.",
    image_url: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
    tags: ["hill-station", "nature", "tea-gardens", "relaxation", "wildlife", "romance"],
    best_season: "Sep - May",
    price_band: "budget",
    latitude: 10.0889,
    longitude: 77.0595,
  },
  {
    id: "dest-rishikesh",
    name: "Rishikesh",
    tagline: "Yoga Capital of the World & Holy Ganga White-Water Rafting",
    description: "Where spiritual ghats meet adrenaline: river rafting, cliff jumping, yoga ashrams, evening Ganga Aarti at Parmarth Niketan, and peaceful riverside cafes.",
    image_url: "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&auto=format&fit=crop&q=80",
    tags: ["adventure", "rafting", "culture", "spiritual", "yoga", "nature"],
    best_season: "Sep - Jun",
    price_band: "budget",
    latitude: 30.0869,
    longitude: 78.2676,
  },
  {
    id: "dest-udaipur",
    name: "Udaipur",
    tagline: "City of Lakes, Royal Luxury & Romantic Sunsets",
    description: "Cruising on Lake Pichola surrounded by Jag Mandir, majestic City Palace, rooftop candle-lit dining, and folk dance performances at Bagore Ki Haveli.",
    image_url: "https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?w=800&auto=format&fit=crop&q=80",
    tags: ["romance", "heritage", "lakes", "culture", "luxury", "food"],
    best_season: "Oct - Mar",
    price_band: "premium",
    latitude: 24.5854,
    longitude: 73.7125,
  },
  {
    id: "dest-hampi",
    name: "Hampi",
    tagline: "Ancient Boulder Kingdom of Vijayanagara Ruins & Hippie Island",
    description: "UNESCO World Heritage site with monolithic stone temples, coracle rides on Tungabhadra river, sunset view from Matanga Hill, and bouldering.",
    image_url: "https://images.unsplash.com/photo-1600100397608-f010e4479901?w=800&auto=format&fit=crop&q=80",
    tags: ["heritage", "archaeology", "adventure", "culture", "boulders", "photography"],
    best_season: "Oct - Feb",
    price_band: "budget",
    latitude: 15.3350,
    longitude: 76.4600,
  },
  {
    id: "dest-pondicherry",
    name: "Pondicherry",
    tagline: "French Colonial Streets, Promenade & Auroville Peace",
    description: "Cobblestone streets lined with bougainvillea, French bakeries, quiet beaches, surfing at Serenity Beach, and spiritual retreat in Auroville.",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    tags: ["culture", "french-heritage", "beach", "cafes", "relaxation", "surfing"],
    best_season: "Oct - Mar",
    price_band: "mid",
    latitude: 11.9416,
    longitude: 79.8083,
  },
  {
    id: "dest-darjeeling",
    name: "Darjeeling",
    tagline: "Queen of the Hills, Kanchenjunga Vistas & Himalayan Toy Train",
    description: "Catch dawn over the snows of Mt. Kanchenjunga from Tiger Hill, ride the heritage steam railway, sip world-renowned first flush tea, and explore Buddhist monasteries.",
    image_url: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",
    tags: ["hill-station", "tea", "mountains", "heritage", "nature", "scenic"],
    best_season: "Oct - Dec, Mar - May",
    price_band: "mid",
    latitude: 27.0410,
    longitude: 88.2663,
  },
  {
    id: "dest-coorg",
    name: "Coorg",
    tagline: "Scotland of India — Coffee Plantations & Misty Waterfalls",
    description: "Lush green Kodagu hills with aromatic Arabica coffee estates, Tibetan Golden Temple at Bylakuppe, Abbey Falls, and traditional Kodava spice cuisine.",
    image_url: "https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?w=800&auto=format&fit=crop&q=80",
    tags: ["nature", "coffee-plantations", "hill-station", "relaxation", "trekking"],
    best_season: "Oct - Apr",
    price_band: "mid",
    latitude: 12.3375,
    longitude: 75.8069,
  },
  {
    id: "dest-varanasi",
    name: "Varanasi",
    tagline: "Eternal Ghats, Dawn Boat Rides & Spiritual Mysticism",
    description: "One of the world's oldest continuously inhabited cities. Experience morning rowing along the Ganga ghats, labyrinthine ancient alleys, Banarasi silk, and soulful Aarti.",
    image_url: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80",
    tags: ["culture", "spiritual", "heritage", "photography", "food"],
    best_season: "Oct - Mar",
    price_band: "budget",
    latitude: 25.3176,
    longitude: 82.9739,
  },
  {
    id: "dest-alleppey",
    name: "Alleppey",
    tagline: "Venice of the East — Houseboat Cruises & Backwaters",
    description: "Drift along palm-fringed canals on a traditional kettuvallam houseboat, enjoy freshly caught Karimeen fish fry, and witness serene village backwater life.",
    image_url: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80",
    tags: ["backwaters", "houseboat", "relaxation", "nature", "food", "romance"],
    best_season: "Nov - Feb",
    price_band: "mid",
    latitude: 9.4981,
    longitude: 76.3388,
  }
];

export const initialHotels = [
  // Goa
  {
    id: "hotel-goa-1",
    destination_id: "dest-goa",
    name: "Taj Fort Aguada Resort & Spa",
    tier: "premium",
    price_per_night: 14500,
    rating: 4.8,
    image_url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80",
    amenities: ["Sea View", "Pool", "Spa", "Private Beach", "Multi-Cuisine"],
    available: true
  },
  {
    id: "hotel-goa-2",
    destination_id: "dest-goa",
    name: "Santana Beach Resort Candolim",
    tier: "mid",
    price_per_night: 4200,
    rating: 4.4,
    image_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80",
    amenities: ["Pool", "2-min walk to Beach", "Breakfast Included", "Bar"],
    available: true
  },
  {
    id: "hotel-goa-3",
    destination_id: "dest-goa",
    name: "Zostel Goa (Anjuna)",
    tier: "budget",
    price_per_night: 1400,
    rating: 4.5,
    image_url: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop&q=80",
    amenities: ["Hostel & Private Rooms", "Rooftop Cafe", "Social Events", "WiFi"],
    available: true
  },
  {
    id: "hotel-goa-4",
    destination_id: "dest-goa",
    name: "Heritage Fontainhas Boutique Inn",
    tier: "mid",
    price_per_night: 3800,
    rating: 4.6,
    image_url: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&auto=format&fit=crop&q=80",
    amenities: ["Historic Quarter", "Heritage Decor", "Artisan Cafe", "Bicycle Rental"],
    available: true
  },

  // Manali
  {
    id: "hotel-manali-1",
    destination_id: "dest-manali",
    name: "The Himalayan Resort & Castle",
    tier: "premium",
    price_per_night: 11500,
    rating: 4.8,
    image_url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80",
    amenities: ["Victorian Gothic Castle", "Fireplace", "Mountain Views", "Heated Pool"],
    available: true
  },
  {
    id: "hotel-manali-2",
    destination_id: "dest-manali",
    name: "Apple Country Resort",
    tier: "mid",
    price_per_night: 4800,
    rating: 4.3,
    image_url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&auto=format&fit=crop&q=80",
    amenities: ["Cedar Woods View", "Spa", "Kids Play Area", "Buffet Breakfast"],
    available: true
  },
  {
    id: "hotel-manali-3",
    destination_id: "dest-manali",
    name: "Zostel Old Manali",
    tier: "budget",
    price_per_night: 1600,
    rating: 4.6,
    image_url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&auto=format&fit=crop&q=80",
    amenities: ["Riverside Cafe", "Common Room", "Bonfire", "High Speed WiFi"],
    available: true
  },

  // Jaipur
  {
    id: "hotel-jaipur-1",
    destination_id: "dest-jaipur",
    name: "Rambagh Palace Heritage",
    tier: "premium",
    price_per_night: 18000,
    rating: 4.9,
    image_url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80",
    amenities: ["Royal Palace Suites", "Peacock Gardens", "Butler Service", "Heritage Walk"],
    available: true
  },
  {
    id: "hotel-jaipur-2",
    destination_id: "dest-jaipur",
    name: "Shahpura House Heritage Hotel",
    tier: "mid",
    price_per_night: 5200,
    rating: 4.5,
    image_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80",
    amenities: ["Traditional Frescoes", "Rooftop Restaurant", "Pool", "Folk Music"],
    available: true
  },
  {
    id: "hotel-jaipur-3",
    destination_id: "dest-jaipur",
    name: "Moustache Hostel Jaipur",
    tier: "budget",
    price_per_night: 1200,
    rating: 4.3,
    image_url: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop&q=80",
    amenities: ["Stepwell Themed Terrace", "Cafe", "Walking Tours", "Budget Friendly"],
    available: true
  },

  // Munnar
  {
    id: "hotel-munnar-1",
    destination_id: "dest-munnar",
    name: "Fragrant Nature Munnar Resort",
    tier: "premium",
    price_per_night: 8500,
    rating: 4.7,
    image_url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80",
    amenities: ["Fireplace in Room", "Tea Valley View", "Ayurvedic Spa"],
    available: true
  },
  {
    id: "hotel-munnar-2",
    destination_id: "dest-munnar",
    name: "Tea County Hill Retreat",
    tier: "mid",
    price_per_night: 3900,
    rating: 4.4,
    image_url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&auto=format&fit=crop&q=80",
    amenities: ["Mountain Valley", "Plantation Tour", "Restaurant"],
    available: true
  },

  // Rishikesh
  {
    id: "hotel-rishikesh-1",
    destination_id: "dest-rishikesh",
    name: "Aloha On The Ganges Resort",
    tier: "premium",
    price_per_night: 9200,
    rating: 4.7,
    image_url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80",
    amenities: ["Infinity Pool over Ganga", "Yoga Sessions", "Spa", "Private Ghat"],
    available: true
  },
  {
    id: "hotel-rishikesh-2",
    destination_id: "dest-rishikesh",
    name: "Zostel Tapovan Rishikesh",
    tier: "budget",
    price_per_night: 1300,
    rating: 4.5,
    image_url: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop&q=80",
    amenities: ["Rooftop Ganga View", "Cafe", "Rafting Desk", "Chill Lounge"],
    available: true
  }
];

export const initialActivities = [
  // Goa activities
  {
    id: "act-goa-1",
    destination_id: "dest-goa",
    name: "Grand Island Scuba Diving & Dolphin Cruise",
    category: "adventure",
    price: 2800,
    duration_minutes: 240,
    opening_time: "07:30",
    closing_time: "13:30",
    tags: ["adventure", "water-sports", "scuba", "marine"],
    image_url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80",
    available: true
  },
  {
    id: "act-goa-2",
    destination_id: "dest-goa",
    name: "Old Goa Heritage Churches & Latin Quarter Walk",
    category: "culture",
    price: 900,
    duration_minutes: 150,
    opening_time: "09:00",
    closing_time: "17:00",
    tags: ["culture", "heritage", "history", "walking-tour"],
    image_url: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
    available: true
  },
  {
    id: "act-goa-3",
    destination_id: "dest-goa",
    name: "Sunset Catamaran Cruise with Live Konkani Music",
    category: "relaxation",
    price: 1500,
    duration_minutes: 120,
    opening_time: "17:00",
    closing_time: "19:30",
    tags: ["sunset", "cruise", "relaxation", "music", "romance"],
    image_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    available: true
  },
  {
    id: "act-goa-4",
    destination_id: "dest-goa",
    name: "Authentic Goan Seafood Tasting Trail in Panjim",
    category: "food",
    price: 1600,
    duration_minutes: 150,
    opening_time: "12:30",
    closing_time: "21:30",
    tags: ["food", "culinary", "seafood", "local-flavor"],
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80",
    available: true
  },
  {
    id: "act-goa-5",
    destination_id: "dest-goa",
    name: "Anjuna Beach Shack Evening & Fire Dance Show",
    category: "nightlife",
    price: 1100,
    duration_minutes: 180,
    opening_time: "19:00",
    closing_time: "23:59",
    tags: ["nightlife", "beach", "party", "cocktails"],
    image_url: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop&q=80",
    available: true
  },

  // Manali activities
  {
    id: "act-manali-1",
    destination_id: "dest-manali",
    name: "Solang Valley Paragliding & Zorbing Adventure",
    category: "adventure",
    price: 3200,
    duration_minutes: 180,
    opening_time: "09:00",
    closing_time: "16:30",
    tags: ["adventure", "paragliding", "flying", "adrenaline"],
    image_url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
    available: true
  },
  {
    id: "act-manali-2",
    destination_id: "dest-manali",
    name: "Jogini Waterfall Cedar Pine Forest Trek",
    category: "adventure",
    price: 800,
    duration_minutes: 180,
    opening_time: "08:30",
    closing_time: "17:00",
    tags: ["trekking", "waterfall", "nature", "scenic"],
    image_url: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&auto=format&fit=crop&q=80",
    available: true
  },
  {
    id: "act-manali-3",
    destination_id: "dest-manali",
    name: "Old Manali Apple Orchard Cafe & Folk Acoustic Session",
    category: "relaxation",
    price: 750,
    duration_minutes: 120,
    opening_time: "11:00",
    closing_time: "21:00",
    tags: ["relaxation", "cafe", "music", "apples"],
    image_url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80",
    available: true
  },
  {
    id: "act-manali-4",
    destination_id: "dest-manali",
    name: "Atal Tunnel & Sissu Lahaul Valley Day Expedition",
    category: "sightseeing",
    price: 2400,
    duration_minutes: 300,
    opening_time: "08:00",
    closing_time: "16:00",
    tags: ["mountains", "tunnel", "lahaul", "snow-peaks"],
    image_url: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",
    available: true
  },

  // Jaipur activities
  {
    id: "act-jaipur-1",
    destination_id: "dest-jaipur",
    name: "Amber Fort Royal Elephant Heritage Tour & Light Show",
    category: "culture",
    price: 1400,
    duration_minutes: 210,
    opening_time: "09:00",
    closing_time: "18:00",
    tags: ["culture", "fort", "royal", "history"],
    image_url: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
    available: true
  },
  {
    id: "act-jaipur-2",
    destination_id: "dest-jaipur",
    name: "Hot Air Balloon Sunrise Flight over Aravali Hills",
    category: "adventure",
    price: 7500,
    duration_minutes: 120,
    opening_time: "05:30",
    closing_time: "08:30",
    tags: ["balloon", "sunrise", "aerial", "luxury"],
    image_url: "https://images.unsplash.com/photo-1507608869274-d3177c8bb4c7?w=800&auto=format&fit=crop&q=80",
    available: true
  },
  {
    id: "act-jaipur-3",
    destination_id: "dest-jaipur",
    name: "Walled City Street Food Tasting & Masala Chai Walk",
    category: "food",
    price: 850,
    duration_minutes: 120,
    opening_time: "16:00",
    closing_time: "20:30",
    tags: ["street-food", "kachori", "chai", "bazaar"],
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80",
    available: true
  },

  // Rishikesh activities
  {
    id: "act-rishikesh-1",
    destination_id: "dest-rishikesh",
    name: "White-Water Ganga River Rafting (16km Shivpuri Run)",
    category: "adventure",
    price: 1200,
    duration_minutes: 180,
    opening_time: "08:00",
    closing_time: "16:00",
    tags: ["rafting", "rapids", "adrenaline", "river"],
    image_url: "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&auto=format&fit=crop&q=80",
    available: true
  },
  {
    id: "act-rishikesh-2",
    destination_id: "dest-rishikesh",
    name: "Sunrise Yoga & Guided Meditation by the Ganga Ghat",
    category: "relaxation",
    price: 600,
    duration_minutes: 90,
    opening_time: "06:00",
    closing_time: "08:30",
    tags: ["yoga", "meditation", "spiritual", "peace"],
    image_url: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&auto=format&fit=crop&q=80",
    available: true
  }
];

export const initialTransport = [
  {
    id: "tr-goa-cab-1",
    from_destination_id: "dest-goa",
    to_destination_id: "dest-goa",
    mode: "cab",
    provider: "Goa Miles Chauffeur SUV",
    duration_minutes: 60,
    price: 1800,
    departure_times: ["08:00", "12:00", "16:00", "20:00"],
    available: true
  },
  {
    id: "tr-goa-scooter-1",
    from_destination_id: "dest-goa",
    to_destination_id: "dest-goa",
    mode: "auto",
    provider: "Coastal Bike & Scooter Rental (Day)",
    duration_minutes: 480,
    price: 600,
    departure_times: ["Anytime 08:00 - 20:00"],
    available: true
  },
  {
    id: "tr-manali-cab-1",
    from_destination_id: "dest-manali",
    to_destination_id: "dest-manali",
    mode: "cab",
    provider: "Himalayan 4x4 Hill Cab",
    duration_minutes: 90,
    price: 2500,
    departure_times: ["08:30", "11:00", "14:30"],
    available: true
  },
  {
    id: "tr-jaipur-cab-1",
    from_destination_id: "dest-jaipur",
    to_destination_id: "dest-jaipur",
    mode: "cab",
    provider: "Royal Rajputana AC Chauffeur",
    duration_minutes: 120,
    price: 1600,
    departure_times: ["09:00", "14:00", "18:00"],
    available: true
  }
];
